prestamo_inicial = float(input("Ingrese Préstamo inicial: "))
tasa_interes = float(input("Ingrese Tasa de interes: "))
tiempo = float(input("Ingrese Tiempo en meses: "))
valor_final = lambda prestamo_inicial, tasa_interes, tiempo: prestamo_inicial * ((1 + tasa_interes / 100) ** tiempo)
valor_prestamo = valor_final(prestamo_inicial, tasa_interes, tiempo)
print("El valor final del préstamo es: " + str(valor_prestamo))